run_script:
  description: Run script on RouterBoard
  fields:
    name:
      description: Name of the saved script
      example: "MySavedScript"

api:
  description: Run api command on RouterBoard
  fields:
    command:
      description: Command
      example: "/ip firewall address-list disable"
    find:
      description: "Find command"
      example: "/ip firewall address-list"
    find_params:
      description: "Parameters to match in find command"
      example: "list=\"internet\" comment=\"test\""